export const initialPlayers = [
  {
    "id": "player_1",
    "name": "PATEL HARSHIL",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/cf53084e-abdc-444c-9d5e-8f909ea94406 - Harshil Patel.jpeg",
    "groupName": "Pavitra",
    "roomNo": 417
  },
  {
    "id": "player_2",
    "name": "Ujjval Gandhi",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_1129 - Ujjval Gandhi.jpeg",
    "groupName": "Pavitra",
    "roomNo": 504
  },
  {
    "id": "player_3",
    "name": "Rudra Patel",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20250305-WA0035 - Rudra Patel.jpg",
    "groupName": "Param",
    "roomNo": 404,
    "bowlingStyle": "Right-arm Fast"
  },
  {
    "id": "player_4",
    "name": "RUSHI ROLA ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/photo 1 - Rushi Rola.jpg",
    "groupName": "Pulkit",
    "roomNo": 717
  },
  {
    "id": "player_5",
    "name": "Dev Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20251217-WA0014 - Dev Patel.jpg",
    "groupName": "Pavitra",
    "roomNo": 304
  },
  {
    "id": "player_6",
    "name": "Manav KiranKumar Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20250918-WA0024 - Manav Kiran Patel.jpg",
    "groupName": "Paramanand",
    "roomNo": 317
  },
  {
    "id": "player_7",
    "name": "Vidhang Sanjay Mundra ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": "G-18"
  },
  {
    "id": "player_8",
    "name": "Meet Hirenbhai Modi",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 505
  },
  {
    "id": "player_9",
    "name": "Kasodiya parth pankaj bhai ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": 802
  },
  {
    "id": "player_10",
    "name": "Shashwat Prajapati",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_1370 - Shashwat Prajapati.jpeg",
    "groupName": "Paramanand",
    "roomNo": 514
  },
  {
    "id": "player_11",
    "name": "Jeet Riteshkumar Solanki",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG20260115145017 - Jeetsinh Solanki.jpg",
    "groupName": "Pulkit",
    "roomNo": 909
  },
  {
    "id": "player_12",
    "name": "Sujal Saraiya ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20240806-WA0113 - Sujal Saraiya.jpg",
    "groupName": "Pulkit",
    "roomNo": "G6"
  },
  {
    "id": "player_13",
    "name": "Sarang patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 915
  },
  {
    "id": "player_14",
    "name": "Mumukshu Patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_7504 - Mumukshu Patel.jpeg",
    "groupName": "Paramanand",
    "roomNo": 212
  },
  {
    "id": "player_15",
    "name": "Patanvadia harshil baldev bhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 6000
  },
  {
    "id": "player_16",
    "name": "Maisuria laksh ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 813
  },
  {
    "id": "player_17",
    "name": "Ambrish Bodra",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1000001403 - Ambrish Bodra.jpg",
    "groupName": "Paramanand",
    "roomNo": 313
  },
  {
    "id": "player_18",
    "name": "Patel manan anilbhai",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 315
  },
  {
    "id": "player_19",
    "name": "Yugkumar Nareshbhai Patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 314
  },
  {
    "id": "player_20",
    "name": "PREM NIMESH KANSARA ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20260118_224922 - Prem Kansara.jpg",
    "groupName": "Paramanand",
    "roomNo": 318
  },
  {
    "id": "player_21",
    "name": "Dhyan bhavikkumar patel ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20251219_135005 - dhyan patel.jpg",
    "groupName": "Pulkit",
    "roomNo": 812
  },
  {
    "id": "player_22",
    "name": "Karm Bopaliya ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": "G-2"
  },
  {
    "id": "player_23",
    "name": " dhairya jivani",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_5418 - Dhairya Jivani.JPG",
    "groupName": "Param",
    "roomNo": 802
  },
  {
    "id": "player_24",
    "name": "Patel Het Tejashbhai",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 7000
  },
  {
    "id": "player_25",
    "name": "Taksh Asalaliya ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/Screenshot_20260118-225228.Photos - Taksh Asalaliya.png",
    "groupName": "Pavitra",
    "roomNo": 307
  },
  {
    "id": "player_26",
    "name": "Joshi Smit ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/20250209_181939 - Joshi Smit.jpg",
    "groupName": "Pavitra",
    "roomNo": 601
  },
  {
    "id": "player_27",
    "name": "Savya Modi",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/3930d280-3573-4ae9-9ca7-7f757f5b1ebb_Original - Savya Modi.jpeg",
    "groupName": "Param",
    "roomNo": 806
  },
  {
    "id": "player_28",
    "name": "Patel Aaditya ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/Screenshot_20251228_162344_Gallery - aaditya patel.jpg",
    "groupName": "Pavitra",
    "roomNo": 417
  },
  {
    "id": "player_29",
    "name": "Priyank Shah",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/20251026_153534 - Priyank Shah.jpg",
    "groupName": "Pulkit",
    "roomNo": "G-4"
  },
  {
    "id": "player_30",
    "name": "Thakor dwip kartik kumar ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 414
  },
  {
    "id": "player_31",
    "name": "Patel harshil dilipkumar",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 306
  },
  {
    "id": "player_32",
    "name": "Dhaivat ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/PHOTO PASSPORT SIZE-2 - Dhaivat Nathwani.pdf",
    "groupName": "Pulkit",
    "roomNo": 818
  },
  {
    "id": "player_33",
    "name": "Aditya dodiya ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20251222_101728_263 - ADITYA DODIYA.webp",
    "groupName": "Pavitra",
    "roomNo": 301
  },
  {
    "id": "player_34",
    "name": "Jenil Jitendrabhai Rank",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20241216_095337 - Jenil Rank.jpg",
    "groupName": "Pavitra",
    "roomNo": 303
  },
  {
    "id": "player_35",
    "name": "Het  Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/b4608bd0-70fe-496c-b257-b09c90cea405 - het patel.jpeg",
    "groupName": "Param",
    "roomNo": 805
  },
  {
    "id": "player_36",
    "name": "Patel Parmesh",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20260115_103304 - Patel Parmesh.jpg",
    "groupName": "Pulkit",
    "roomNo": 813
  },
  {
    "id": "player_37",
    "name": "Aditya Jetly",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/Aditya pic 120_120 - Aditya Jetly.jpg",
    "groupName": "Paramanand",
    "roomNo": 211
  },
  {
    "id": "player_38",
    "name": "Piku Bhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 7000
  },
  {
    "id": "player_39",
    "name": "Patel Bhavyakumar Ashishkumar ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": 801
  },
  {
    "id": "player_40",
    "name": "Preet Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20250608-WA0006 - Preet Patel.jpg",
    "groupName": "Pavitra",
    "roomNo": 609
  },
  {
    "id": "player_41",
    "name": "Bhalgamiya deep jitendrabhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 416
  },
  {
    "id": "player_42",
    "name": "Vedant patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1000083514 - Vedant Patel.jpg",
    "groupName": "Paramanand",
    "roomNo": 317
  },
  {
    "id": "player_43",
    "name": "Prerak Patel",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_1496 - Prerak Patel.jpeg",
    "groupName": "Paramanand",
    "roomNo": "G1"
  },
  {
    "id": "player_44",
    "name": "Adityarajsinh Gohil ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/20260111_232009 - Gohil Adityarajsinh.jpg",
    "groupName": "Paramanand",
    "roomNo": 216
  },
  {
    "id": "player_45",
    "name": "Dhruv Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20260115-WA0008 - Dhruv Patel.jpg",
    "groupName": "Pulkit",
    "roomNo": 818
  },
  {
    "id": "player_46",
    "name": "Vishal T. Patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/20260105_082515(1) - Vishal Patel.jpg",
    "groupName": "Pavitra",
    "roomNo": 607
  },
  {
    "id": "player_47",
    "name": "Patel Kirtan ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1758603616019 - Kirtan Patel.jpg",
    "groupName": "Pavitra",
    "roomNo": 414
  },
  {
    "id": "player_48",
    "name": "Prince HarishBhai patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20241106_003550 - Prince Patel.jpg",
    "groupName": "Paramanand",
    "roomNo": 708
  },
  {
    "id": "player_49",
    "name": "Kirtan Sandipkumar Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1758603616019 - Kirtan Patel.jpg",
    "groupName": "Pulkit",
    "roomNo": 718
  },
  {
    "id": "player_50",
    "name": "Kavan Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/WhatsApp Image 2025-09-24 at 10.25.23_34fb7faf - Kavan Patel.jpg",
    "groupName": "Paramanand",
    "roomNo": 516
  },
  {
    "id": "player_51",
    "name": "Dish Alagiya ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20250209-WA0013 - Dish Alagiya.jpg",
    "groupName": "Param",
    "roomNo": "G 10"
  },
  {
    "id": "player_52",
    "name": "Devansh Jatinbhai Rajpura ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/20250531_132632 (1) (1) - Devansh Rajpura.jpg",
    "groupName": "Pulkit",
    "roomNo": 908
  },
  {
    "id": "player_53",
    "name": "Sanyam mistry",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_6436 - Sanyam Mistry.jpeg",
    "groupName": "Pavitra",
    "roomNo": 3000
  },
  {
    "id": "player_54",
    "name": "Het Vanani ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20240710-WA0003 - Het Vanani.jpg",
    "groupName": "Paramanand",
    "roomNo": 709
  },
  {
    "id": "player_55",
    "name": "Vatsal patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1766337110691 - Vatsal Patel.jpg",
    "groupName": "Pavitra",
    "roomNo": 416
  },
  {
    "id": "player_56",
    "name": "Mistry Viral Jayeshbhai",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 707
  },
  {
    "id": "player_57",
    "name": "Vaghasiya Yash N.",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 715
  },
  {
    "id": "player_58",
    "name": "Yug Hiteshbhai Dadhania ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/image - Yug Dadhania.jpg",
    "groupName": "Paramanand",
    "roomNo": 704
  },
  {
    "id": "player_59",
    "name": "Kunj Sanjaybhai Dhameliya",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_9152 - Kunj Dhameliya.jpeg",
    "groupName": "Pavitra",
    "roomNo": 411
  },
  {
    "id": "player_60",
    "name": "Patel Rudra Anilbhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 410
  },
  {
    "id": "player_61",
    "name": "Sudhanshu Bhimani",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 915
  },
  {
    "id": "player_62",
    "name": "Dip Baldha ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": "G - 3"
  },
  {
    "id": "player_63",
    "name": "Tishy Nirmesh Desai",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/Tishy Image - Tishy Desai.jpg",
    "groupName": "Pavitra",
    "roomNo": 505
  },
  {
    "id": "player_64",
    "name": "Krish Dalsaniya",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20260118_234119 - Krish Dalsaniya.jpg",
    "groupName": "Pulkit",
    "roomNo": 901
  },
  {
    "id": "player_65",
    "name": "Avaiya vansh rakeshkumar ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 907
  },
  {
    "id": "player_66",
    "name": "Mantra Rajyaguru ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/20260117_095324 - MANTRA RAJYAGURU.jpg",
    "groupName": "Pavitra",
    "roomNo": 209
  },
  {
    "id": "player_67",
    "name": "Karan Jayeshbhai Tarsariya ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 906
  },
  {
    "id": "player_68",
    "name": "Ved Amitkumar Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1000083514 - Vedant Patel.jpg",
    "groupName": "Param",
    "roomNo": 616
  },
  {
    "id": "player_69",
    "name": "Om.S.Joshi",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 309
  },
  {
    "id": "player_70",
    "name": "Yug khunt ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 309
  },
  {
    "id": "player_71",
    "name": "Tajapa sujal jayeshbhai",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": 8000
  },
  {
    "id": "player_72",
    "name": "Aadhya Dave",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/20250827_121856 - Aadhya Dave.heic",
    "groupName": "Param",
    "roomNo": 201
  },
  {
    "id": "player_73",
    "name": "Param Vinodbhai Patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1751351630539 - Param Patel.jpg",
    "groupName": "Paramanand",
    "roomNo": 515
  },
  {
    "id": "player_74",
    "name": "Khalasi Dimpesh bakulbhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": 402
  },
  {
    "id": "player_75",
    "name": "Divyesh Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20250617_194546_874 - DIVYESH PATEL.webp",
    "groupName": "Param",
    "roomNo": 805
  },
  {
    "id": "player_76",
    "name": "Patel vidit ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1000028949 - Vidit Patel.jpg",
    "groupName": "Paramanand",
    "roomNo": 914
  },
  {
    "id": "player_77",
    "name": "Shrey Nikhilkumar Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1000057512 - Shrey Patel.jpg",
    "groupName": "Pulkit",
    "roomNo": 815
  },
  {
    "id": "player_78",
    "name": "Renish hiteshbhai bhavani ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1000095985 - RENISH BHAVANI.jpg",
    "groupName": "Param",
    "roomNo": "G-13"
  },
  {
    "id": "player_79",
    "name": "Meet Sanjaykumar Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20250512_175819_074 - Meet Patel.webp",
    "groupName": "Pavitra",
    "roomNo": 603
  },
  {
    "id": "player_80",
    "name": "Patel Vraj Nileshkumar ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 501
  },
  {
    "id": "player_81",
    "name": "Smit Mahida",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_9707 - Smit Mahida.jpeg",
    "groupName": "Pulkit",
    "roomNo": 810
  },
  {
    "id": "player_82",
    "name": "Desai Prince jayeshbhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 706
  },
  {
    "id": "player_83",
    "name": "Parmar Aniket Bipinbhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 6000
  },
  {
    "id": "player_84",
    "name": "Parshva Modi Nikunjkumar ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 515
  },
  {
    "id": "player_85",
    "name": "Mihir Tank",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20250726_101045 - Mihir Tank.jpg",
    "groupName": "Pavitra",
    "roomNo": 503
  },
  {
    "id": "player_86",
    "name": "Dhruv Jasani",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_6264 - Dhruv Jasani.jpeg",
    "groupName": "Pavitra",
    "roomNo": 602
  },
  {
    "id": "player_87",
    "name": "Dish Alagiya",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20250209-WA0013 - Dish Alagiya.jpg",
    "groupName": "Param",
    "roomNo": "G 10"
  },
  {
    "id": "player_88",
    "name": "Patel Nisarg ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20250711-WA0004 - Patel Nisarg.jpg",
    "groupName": "Param",
    "roomNo": 618
  },
  {
    "id": "player_89",
    "name": "Kachhadiya Maharshi ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20250624_090137 - Maharshi Kachhadiya.jpg",
    "groupName": "Pulkit",
    "roomNo": 717
  },
  {
    "id": "player_90",
    "name": "Vrajesh Rana",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20260119_094345 - Vrajesh Rana.jpg",
    "groupName": "Pavitra",
    "roomNo": 608
  },
  {
    "id": "player_91",
    "name": "Kanani Adarsh Mukeshbhai ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": 405
  },
  {
    "id": "player_92",
    "name": "Patel Vivek ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/file_00000000e16471fdb627a3877df31c8c - Patel Vivek.jpg",
    "groupName": "Param",
    "roomNo": 402
  },
  {
    "id": "player_93",
    "name": "Ayush Hareshbhai Mistry",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/Ayush Mistry - Ayush Mistry.png",
    "groupName": "Param",
    "roomNo": 4000
  },
  {
    "id": "player_94",
    "name": "harshil Kaushikbhai Patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/cf53084e-abdc-444c-9d5e-8f909ea94406 - Harshil Patel.jpeg",
    "groupName": "Pavitra",
    "roomNo": 608
  },
  {
    "id": "player_95",
    "name": "Krushitsinh Alonja",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 216
  },
  {
    "id": "player_96",
    "name": "Pratik vasava",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_1359 - VASAVA PRATIK.JPG",
    "groupName": "Param",
    "roomNo": 612
  },
  {
    "id": "player_97",
    "name": "Jeet Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/-6091427592386227984_121 - Jeet Patel.jpg",
    "groupName": "Paramanand",
    "roomNo": 918
  },
  {
    "id": "player_98",
    "name": "Tadvi Prasadbhai Devjibhai ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 601
  },
  {
    "id": "player_99",
    "name": "Ayush Ahir",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1742605190749 - Ayush Ahir.jpg",
    "groupName": "Pavitra",
    "roomNo": 3000
  },
  {
    "id": "player_100",
    "name": "Desai Meetkumar Jayarambhai ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 918
  },
  {
    "id": "player_101",
    "name": "Gevariya Ansh Arvindbhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": "G-12"
  },
  {
    "id": "player_102",
    "name": "Parth Prajapati ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/20260114_174910 - Parth Prajapati.jpg",
    "groupName": "Paramanand",
    "roomNo": 910
  },
  {
    "id": "player_103",
    "name": "Sevant desai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20250518-WA0008 - Desai Sevant.jpg",
    "groupName": "Paramanand",
    "roomNo": 9000
  },
  {
    "id": "player_104",
    "name": "Patel meet ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20250512_175819_074 - Meet Patel.webp",
    "groupName": "Pulkit",
    "roomNo": 817
  },
  {
    "id": "player_105",
    "name": "Anand solanki",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 3000
  },
  {
    "id": "player_106",
    "name": "Poojan Patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/photo - Poojan Patel.jpeg",
    "groupName": "Paramanand",
    "roomNo": 313
  },
  {
    "id": "player_107",
    "name": "Manik Mandal ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/14819 - Manik Mandal.png",
    "groupName": "Param",
    "roomNo": 403
  },
  {
    "id": "player_108",
    "name": "Patel bhavya mukeshbhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 702
  },
  {
    "id": "player_109",
    "name": "Shrey manaharbhai patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1000057512 - Shrey Patel.jpg",
    "groupName": "Param",
    "roomNo": 804
  },
  {
    "id": "player_110",
    "name": "Tikiwala Manan Jatin Kumar ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 708
  },
  {
    "id": "player_111",
    "name": "Dhruvil patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_6351 - Dhruvil Patel.png",
    "groupName": "Paramanand",
    "roomNo": 215
  },
  {
    "id": "player_112",
    "name": "PRAJAPATI BHARGAV PRAVINBHAI ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 6000
  },
  {
    "id": "player_113",
    "name": "Aryansinh Dashrathbhai Chauhan ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20251229_171650 - Aryansinh Chauhan.jpg",
    "groupName": "Pulkit",
    "roomNo": "G-5"
  },
  {
    "id": "player_114",
    "name": "Bopaliya Smit Bipinbhai ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": "G-6"
  },
  {
    "id": "player_115",
    "name": "Kirtan padhiyar",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20250722-WA0052 - Kirtan Padhiyar.jpg",
    "groupName": "Pulkit",
    "roomNo": 7000
  },
  {
    "id": "player_116",
    "name": "Patel Het Prakashbhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 315
  },
  {
    "id": "player_117",
    "name": "Rushi Ashwinbhai Patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20251217_213851_710 - Rushi Patel.webp",
    "groupName": "Pavitra",
    "roomNo": 418
  },
  {
    "id": "player_118",
    "name": "Jatin Amit  Bodhe ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/EC5B5488-EFA5-464B-B132-39337C23A6CB - Jatin Bodhe Pawar.jpeg",
    "groupName": "Param",
    "roomNo": "G-18  "
  },
  {
    "id": "player_119",
    "name": "Het patel ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/b4608bd0-70fe-496c-b257-b09c90cea405 - het patel.jpeg",
    "groupName": "Pavitra",
    "roomNo": 607
  },
  {
    "id": "player_120",
    "name": "Patel Parshva Ashokkumar ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": "G-14"
  },
  {
    "id": "player_121",
    "name": "Himanshu Anil Singh",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 157
  },
  {
    "id": "player_122",
    "name": "Rushi patel",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20251217_213851_710 - Rushi Patel.webp",
    "groupName": "Param",
    "roomNo": "G-17"
  },
  {
    "id": "player_123",
    "name": "Patel Dhyey ashok bhai",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 913
  },
  {
    "id": "player_124",
    "name": "Rana Shashwat ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20250922_101750288 (1) - Shashwat Rana.jpg",
    "groupName": "Pavitra",
    "roomNo": 306
  },
  {
    "id": "player_125",
    "name": "Patel Param",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1751351630539 - Param Patel.jpg",
    "groupName": "Pulkit",
    "roomNo": 906
  },
  {
    "id": "player_126",
    "name": "Pavitra Modi",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_3421 - Pavitra Modi.jpeg",
    "groupName": "Param",
    "roomNo": 401
  },
  {
    "id": "player_127",
    "name": "Smit Naresh Parekh",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/NEW-PHOTO - Smit Parekh.jpeg",
    "groupName": "Param",
    "roomNo": 613
  },
  {
    "id": "player_128",
    "name": "Nirdosh patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/20251122_104420 - Nirdosh patel.jpg",
    "groupName": "Pavitra",
    "roomNo": 151
  },
  {
    "id": "player_129",
    "name": "Vinit Patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_7964 - Vinit Patel.jpeg",
    "groupName": "Param",
    "roomNo": 804
  },
  {
    "id": "player_130",
    "name": "Yagnik",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 412
  },
  {
    "id": "player_131",
    "name": "Dhairya Soni",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": "G13"
  },
  {
    "id": "player_132",
    "name": "Bhuva Smit ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 8
  },
  {
    "id": "player_133",
    "name": "Tandel sarvamkumar dineshkumar ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 6000
  },
  {
    "id": "player_134",
    "name": "udani kavan bharatbhai",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 304
  },
  {
    "id": "player_135",
    "name": "Dharmik Suthar",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/WhatsApp Image 2026-01-19 at 22.06.44 - Dharmik Suthar.jpeg",
    "groupName": "Pavitra",
    "roomNo": 305
  },
  {
    "id": "player_136",
    "name": "Sachin Gajera ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/DSC_0126_053439 - Sachin Gajera.jpg",
    "groupName": "Param",
    "roomNo": 8000
  },
  {
    "id": "player_137",
    "name": "NEEL PATEL",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20260119_220826 - neel Patel.jpg",
    "groupName": "Pulkit",
    "roomNo": 7000
  },
  {
    "id": "player_138",
    "name": "manthan bhalara",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 318
  },
  {
    "id": "player_139",
    "name": "Sruhad nileshbhai patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_7561 - Sruhad Patel.JPG",
    "groupName": "Pavitra",
    "roomNo": 509
  },
  {
    "id": "player_140",
    "name": "DHRUV RANA ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20260119_094703 - Dhruv Rana.jpg",
    "groupName": "Pavitra",
    "roomNo": 502
  },
  {
    "id": "player_141",
    "name": "Kevin vachhani ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_8314 - Kevin Vachhani.JPG",
    "groupName": "Param",
    "roomNo": 615
  },
  {
    "id": "player_142",
    "name": "Jithara Tirth ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG-20250607-WA0006 - Tirth Jithara.jpg",
    "groupName": "Param",
    "roomNo": 405
  },
  {
    "id": "player_143",
    "name": "Javia Nihal R ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": 615
  },
  {
    "id": "player_144",
    "name": "Meet gajera ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/20251007_204841 - Meet Gajera.heic",
    "groupName": "Pavitra",
    "roomNo": 602
  },
  {
    "id": "player_145",
    "name": "Divya Patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Paramanand",
    "roomNo": 705
  },
  {
    "id": "player_146",
    "name": "Kavy kakadiya ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/1768547069132 - Kavy Kakadiya.jpg",
    "groupName": "Param",
    "roomNo": 604
  },
  {
    "id": "player_147",
    "name": "Italiya Dhyey Arvindbhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 902
  },
  {
    "id": "player_148",
    "name": "Bhingradiya Vasu Rameshbhai ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pavitra",
    "roomNo": 3000
  },
  {
    "id": "player_149",
    "name": "MAHRSHI",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20260120_163145 - Mahrshi Patel.jpg",
    "groupName": "Paramanand",
    "roomNo": 514
  },
  {
    "id": "player_150",
    "name": "Radhod dhrumilsinh",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": "G-5"
  },
  {
    "id": "player_151",
    "name": "Shreemad Rajeshkumar Gandhi",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_4604 - Shreemad Gandhi.jpeg",
    "groupName": "Pulkit",
    "roomNo": 710
  },
  {
    "id": "player_152",
    "name": "Patel Jal Prakashkumar ",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Pulkit",
    "roomNo": 816
  },
  {
    "id": "player_153",
    "name": "JINIL P Patel",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/Screenshot_20260121_153117 - Jinil patel.jpg",
    "groupName": "Pavitra",
    "roomNo": 303
  },
  {
    "id": "player_154",
    "name": "Heet Nasit",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_7665 - HEET NASIT.jpeg",
    "groupName": "Pulkit",
    "roomNo": 218
  },
  {
    "id": "player_155",
    "name": "Param Gandhi ",
    "role": "Batsman",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": "/images/IMG_20250124_081053_932 - param gandhi.webp",
    "groupName": "Paramanand",
    "roomNo": 707
  },
  {
    "id": "player_156",
    "name": "Gevariya Tirth Hareshbhai",
    "role": "Bowler",
    "basePrice": 3,
    "currentPrice": 3,
    "status": "unsold",
    "imageUrl": null,
    "groupName": "Param",
    "roomNo": "G17"
  }
];
